### ISSUE TITLE
Inconsistent coding convention

### ISSUE THREAD

**Issue by davidnguyen179** [kogp112/react_todo_list#1]
Here is some things I found that makes code inconsistent:

**Single quote**
**Do**
```js
const greeting = 'hello world';
```

**Don't**
```js
const greeting = "hello world";
```

**Indent**

Should use 2 spaces instead of tab.
**Do**
```js
if (true) {
  console.log('Hello world');
}
```

**Don't**
```js
if (true) {
        console.log('Hello world');
}
```

**Arrow function**
Should use the arrow function when some methods access to `this` value. `Arrow function` automatically bind the `this` to the method. So that we don't need to manually do bind `this` at the `constructor`.

For example:

```js
this.handleChange = this.handleChange.bind(this);

handleChange(event) {
  this.setState({[event.target.name]: event.target.value});
}
```

is the same with

```js
handleChange = (event) => {
  ...
}
```

**Comment by kogp112** [comment]
Thank you for your mention! I will modify that. 💪
